//
//  ItineraryViewModel.swift
//  Lux
//
//  Created by Constantin Clerc on 23.04.2025.
//

import SwiftUI
import MapKit
import LuxCom
import Polyline

@MainActor
final class ItineraryViewModel: ObservableObject {
    @Published var tripId: String
    private let zoomThreshold: CLLocationDistance = 50000
    private let vehicleUpdateInterval: Duration = .seconds(2)
    private let walkingUpdateInterval: Duration = .seconds(1)
    private let maxRouteOverlayPointsPerLeg = 450
    private let maxWalkingPathPointsPerLeg = 220

    private struct WalkingPathMetrics {
        let coordinates: [CLLocationCoordinate2D]
        let cumulativeDistances: [CLLocationDistance]
        let totalDistance: CLLocationDistance
    }

    private var legKeyFrames: [String: [VehicleVisualisation.KeyFrame]] = [:]
    private var walkingLegPaths: [String: WalkingPathMetrics] = [:]
    private var vehicleUpdateTask: Task<Void, Never>?
    private var walkingUpdateTask: Task<Void, Never>?
    private let liveFeed = RelayLiveFeed<Itinerary>()
    
    private var shouldStop = false
    
    @Published var itinerary: Itinerary?
    @Published var selectedStop: Place? = nil
    @Published var position: MapCameraPosition = .automatic
    @Published var mapAnnotations: [StopAnnotation] = []
    @Published var routeOverlays: [RouteOverlay] = []
    @Published var showingIntermediateStops: Bool = true
    @Published var vehicleAnnotations: [VehicleAnnotation] = []
    @Published var walkingAnnotations: [WalkingAnnotation] = []
    @Published var isLoading: Bool = true
    @Published var error: String?
    @Published var walkingDirections: [String: [MKRoute.Step]] = [:]
    @ObservedObject var settings = Settings.shared
        
    private(set) var destinationName: String?

    init(tripId: String) {
        self.tripId = tripId
    }
    
    convenience init(itinerary: Itinerary, destinationName: String? = nil) {
        self.init(tripId: "")
        self.itinerary = itinerary
        self.destinationName = destinationName
    }
        
    func switchToTrip(tripId: String) async {
        guard tripId != self.tripId else { return }
        
        stopAllTasks()
        
        self.vehicleAnnotations = []
        self.walkingAnnotations = []
        self.tripId = tripId
        self.itinerary = nil
        self.mapAnnotations = []
        self.routeOverlays = []
        self.walkingDirections = [:]
        self.legKeyFrames = [:]
        self.walkingLegPaths = [:]
        self.error = nil
        self.shouldStop = false
        self.selectedStop = nil
        
        await loadItinerary()
    }
    
    func stopAllTasks() {
        shouldStop = true
        stopItineraryRefresh()
        stopVehicleUpdates()
        stopWalkingUpdates()
    }
    
    func loadItinerary() async {
        guard !shouldStop else { return }
        
        if itinerary != nil {
            await processItinerary()
            await refreshItinerary(dontActuallyFetch: true)
            isLoading = false
            startItineraryRefresh()
            return
        }
        
        isLoading = true
        error = nil
        
        if !OfflineRouter.shared.isOfflineActive, await RelayClient.shared.isConnected {
            startItineraryRefresh()
            return
        }

        do {
            itinerary = try await LuxData.trip(tripId: tripId)
            if itinerary != nil {
                await processItinerary()
                startItineraryRefresh()
            } else {
                error = "No itinerary data found"
            }
        } catch {
            self.error = error.localizedDescription
        }
        
        isLoading = false
    }
    
    // MKDirections
    func fetchWalkingDirections(for leg: Leg) async {
        guard leg.mode == .walk else { return }
        
        let legId = getLegIdentifier(leg)
        
        if walkingDirections[legId] != nil {
            return
        }
        
        let request = MKDirections.Request()
        
        let sourceCoordinate = CLLocationCoordinate2D(latitude: leg.from.lat, longitude: leg.from.lon)
        let destinationCoordinate = CLLocationCoordinate2D(latitude: leg.to.lat, longitude: leg.to.lon)
        
        request.source = MKMapItem(placemark: MKPlacemark(coordinate: sourceCoordinate))
        request.destination = MKMapItem(placemark: MKPlacemark(coordinate: destinationCoordinate))
        request.transportType = .walking
        
        let directions = MKDirections(request: request)
        
        do {
            let response = try await directions.calculate()
            if let route = response.routes.first {
                var steps = route.steps
                
                if steps.count > 2 {
                    // those remove head to/arrive to generated by mkdirections
                    steps.removeFirst()
                    steps.removeLast()
                }
                
                await MainActor.run {
                    walkingDirections[legId] = steps
                }
            }
        } catch {
            print("failed to calculate walking directions for leg \(legId) !!! \(error)")
        }
    }
        
    /// Live trip updates via the relay WebSocket; the legacy 10s HTTP poll
    /// only runs while the socket is down or in offline mode.
    private func startItineraryRefresh() {
        guard !tripId.isEmpty && !shouldStop else { return }

        stopItineraryRefresh()

        let tripId = tripId

        liveFeed.start(
            fallbackOnly: OfflineRouter.shared.isOfflineActive,
            fallbackInterval: .seconds(10),
            stream: {
                await RelayClient.shared.trip(tripId: tripId)
            },
            fallbackFetch: {
                try? await LuxData.trip(tripId: tripId)
            },
            onUpdate: { [weak self] newItinerary in
                guard let self, !self.shouldStop else { return }
                let isInitialLoad = self.itinerary == nil
                self.itinerary = newItinerary
                self.isLoading = false
                Task { await self.processItinerary(shouldCalculateMapPosition: isInitialLoad) }
            }
        )
    }

    private func stopItineraryRefresh() {
        liveFeed.stop()
    }
    
    private func refreshItinerary(dontActuallyFetch: Bool = false) async {
        guard !tripId.isEmpty && !shouldStop else { return }
        
        do {
            if !dontActuallyFetch {
                let newItinerary = try await LuxData.trip(tripId: tripId)
                itinerary = newItinerary
            }
            else {
                // Keep current snapshot without triggering a no-op publish.
            }
            
            await processItinerary(shouldCalculateMapPosition: false)
        } catch {
            print("failed to refresh! \(error.localizedDescription)")
        }
    }
    
    func updateZoomLevel(distance: CLLocationDistance) {
        let shouldShowIntermediateStops = distance < zoomThreshold
        guard shouldShowIntermediateStops != showingIntermediateStops else { return }
        showingIntermediateStops = shouldShowIntermediateStops
    }
    
    private func processItinerary(shouldCalculateMapPosition: Bool = true) async {
        guard let itinerary = itinerary, !shouldStop else {
            error = "Missing itinerary data"
            return
        }
                
        let (annotations, overlays) = createAnnotationsAndOverlays(for: itinerary)
        mapAnnotations = annotations
        routeOverlays = overlays

        if shouldCalculateMapPosition {
            calculateMapPosition()
        }
        
        if settings.fetchWalkingDirectionsUsingMKDirections {
            await fetchWalkingDirectionsForAllLegs(itinerary.legs)
        }
        
        prepareWalkingLegCoordinates(for: itinerary.legs)
        prepareVehicleKeyframes(for: itinerary.legs)
        
        startVehicleUpdates()
        startWalkingUpdates()
    }
    
    private func fetchWalkingDirectionsForAllLegs(_ legs: [Leg]) async {
        await withTaskGroup(of: Void.self) { group in
            for leg in legs where leg.mode == .walk {
                group.addTask {
                    await self.fetchWalkingDirections(for: leg)
                }
            }
        }
    }
    
    private func prepareVehicleKeyframes(for legs: [Leg]) {
        guard !shouldStop else { return }
        
        legKeyFrames.removeAll()
        
        for leg in legs where leg.mode != .walk && leg.mode != .bike {
            let legId = getLegIdentifier(leg)
            let keyFrames = VehicleVisualisation.calculateKeyFrames(for: leg, polylineString: leg.legGeometry.points, precision: 1e6)
            legKeyFrames[legId] = keyFrames
        }
    }
    
    private func prepareWalkingLegCoordinates(for legs: [Leg]) {
        guard !shouldStop else { return }
        
        walkingLegPaths.removeAll()
        
        for leg in legs where leg.mode == .walk {
            let legId = getLegIdentifier(leg)
            let polyline = Polyline(encodedPolyline: leg.legGeometry.points, precision: 1e6)
            
            if let coordinates = polyline.coordinates, coordinates.count >= 2 {
                let simplifiedCoordinates = reduceCoordinatesIfNeeded(
                    coordinates,
                    maxPoints: maxWalkingPathPointsPerLeg
                )
                self.walkingLegPaths[legId] = buildWalkingPathMetrics(from: simplifiedCoordinates)
            } else {
                let from = CLLocationCoordinate2D(latitude: leg.from.lat, longitude: leg.from.lon)
                let to = CLLocationCoordinate2D(latitude: leg.to.lat, longitude: leg.to.lon)
                let fallbackCoordinates = [from, to]
                self.walkingLegPaths[legId] = buildWalkingPathMetrics(from: fallbackCoordinates)
            }
        }
    }

    private func buildWalkingPathMetrics(from coordinates: [CLLocationCoordinate2D]) -> WalkingPathMetrics {
        guard !coordinates.isEmpty else {
            return WalkingPathMetrics(coordinates: [], cumulativeDistances: [], totalDistance: 0)
        }

        if coordinates.count == 1 {
            return WalkingPathMetrics(coordinates: coordinates, cumulativeDistances: [0], totalDistance: 0)
        }

        var cumulativeDistances: [CLLocationDistance] = [0]
        cumulativeDistances.reserveCapacity(coordinates.count)

        var totalDistance: CLLocationDistance = 0
        for index in 1..<coordinates.count {
            totalDistance += coordinates[index - 1].distance(to: coordinates[index])
            cumulativeDistances.append(totalDistance)
        }

        return WalkingPathMetrics(
            coordinates: coordinates,
            cumulativeDistances: cumulativeDistances,
            totalDistance: totalDistance
        )
    }

    private func reduceCoordinatesIfNeeded(
        _ coordinates: [CLLocationCoordinate2D],
        maxPoints: Int
    ) -> [CLLocationCoordinate2D] {
        guard coordinates.count > maxPoints, maxPoints > 2 else { return coordinates }

        let lastIndex = coordinates.count - 1
        let step = Double(lastIndex) / Double(maxPoints - 1)
        var reducedCoordinates: [CLLocationCoordinate2D] = []
        reducedCoordinates.reserveCapacity(maxPoints)
        reducedCoordinates.append(coordinates[0])

        for reducedIndex in 1..<(maxPoints - 1) {
            let sourceIndex = Int((Double(reducedIndex) * step).rounded())
            let clampedSourceIndex = min(max(sourceIndex, 1), lastIndex - 1)
            reducedCoordinates.append(coordinates[clampedSourceIndex])
        }

        reducedCoordinates.append(coordinates[lastIndex])
        return reducedCoordinates
    }
    
    func getLegIdentifier(_ leg: Leg) -> String {
        "\(leg.routeShortName ?? "")_\(leg.headsign ?? "")_\(leg.startTime.timeIntervalSince1970)"
    }
    
    private func startVehicleUpdates() {
        guard !shouldStop else { return }
        guard !legKeyFrames.isEmpty else {
            vehicleAnnotations = []
            return
        }
        
        stopVehicleUpdates()
        
        vehicleUpdateTask = Task {
            while !Task.isCancelled && !shouldStop {
                updateVehiclePositions()
                try? await Task.sleep(for: vehicleUpdateInterval)
            }
        }
    }
    
    private func startWalkingUpdates() {
        guard !shouldStop, walkingUpdateTask == nil else { return }
        guard !walkingLegPaths.isEmpty else {
            walkingAnnotations = []
            return
        }
        
        walkingUpdateTask = Task {
            while !Task.isCancelled && !shouldStop {
                updateWalkingPositions()
                try? await Task.sleep(for: walkingUpdateInterval)
            }
        }
    }

    deinit {
        shouldStop = true
        vehicleUpdateTask?.cancel()
        walkingUpdateTask?.cancel()
        // liveFeed cancels its own tasks in its deinit
        vehicleUpdateTask = nil
        walkingUpdateTask = nil
    }
    
    private func stopVehicleUpdates() {
        vehicleUpdateTask?.cancel()
        vehicleUpdateTask = nil
    }
    
    private func stopWalkingUpdates() {
        walkingUpdateTask?.cancel()
        walkingUpdateTask = nil
    }

    private func updateVehiclePositions() {
        guard let itinerary = itinerary, !shouldStop else { return }
        
        let currentTime = Date()
        let currentTimeInterval = currentTime.timeIntervalSince1970
        
        let newVehicleAnnotations = itinerary.legs.compactMap { leg -> VehicleAnnotation? in
            guard leg.mode != .walk && leg.mode != .bike else { return nil }
            
            guard leg.startTime <= currentTime && leg.endTime >= currentTime else { return nil }
            
            let legId = getLegIdentifier(leg)
            
            guard let keyFrames = legKeyFrames[legId],
                  let position = VehicleVisualisation.interpolatePosition(
                    at: currentTimeInterval,
                    using: keyFrames
                  ) else { return nil }
            
            return VehicleAnnotation(
                id: legId,
                coordinate: position,
                routeShortName: leg.routeShortName,
                color: getLegColor(leg)
            )
        }

        withAnimation(.easeInOut(duration: 0.5)) {
            vehicleAnnotations = newVehicleAnnotations
        }
    }
    
    private func updateWalkingPositions() {
        guard let itinerary = itinerary, !shouldStop else { return }
        
        let currentTime = Date()
        let currentTimeInterval = currentTime.timeIntervalSince1970
        
        let newWalkingAnnotations = itinerary.legs.compactMap { leg -> WalkingAnnotation? in
            guard leg.mode == .walk else { return nil }
            
            guard leg.startTime <= currentTime && leg.endTime >= currentTime else { return nil }
            
            let legId = getLegIdentifier(leg)
            guard let position = walkingPosition(for: leg, legId: legId, at: currentTimeInterval) else { return nil }
            
            return WalkingAnnotation(id: legId, coordinate: position)
        }

        withAnimation(.linear(duration: 1.0)) {
            walkingAnnotations = newWalkingAnnotations
        }
    }
    
    private func walkingPosition(for leg: Leg, legId: String, at timestamp: TimeInterval) -> CLLocationCoordinate2D? {
        let startTime = leg.startTime.timeIntervalSince1970
        let endTime = leg.endTime.timeIntervalSince1970
        
        guard endTime > startTime else {
            return CLLocationCoordinate2D(latitude: leg.from.lat, longitude: leg.from.lon)
        }
        
        let progress = max(0, min(1, (timestamp - startTime) / (endTime - startTime)))
        
        if let pathMetrics = walkingLegPaths[legId], let coordinate = interpolateOnPath(pathMetrics, progress: progress) {
            return coordinate
        }
        
        let from = CLLocationCoordinate2D(latitude: leg.from.lat, longitude: leg.from.lon)
        let to = CLLocationCoordinate2D(latitude: leg.to.lat, longitude: leg.to.lon)
        return interpolateCoordinate(from: from, to: to, progress: progress)
    }
    
    private func interpolateOnPath(_ pathMetrics: WalkingPathMetrics, progress: Double) -> CLLocationCoordinate2D? {
        let coordinates = pathMetrics.coordinates
        guard let first = coordinates.first else { return nil }
        guard let last = coordinates.last else { return first }
        
        if coordinates.count == 1 || progress <= 0 {
            return first
        }
        
        if progress >= 1 {
            return last
        }
        
        guard pathMetrics.totalDistance > 0 else { return first }

        let targetDistance = pathMetrics.totalDistance * progress
        let cumulativeDistances = pathMetrics.cumulativeDistances

        for index in 1..<cumulativeDistances.count {
            let traversedDistance = cumulativeDistances[index - 1]
            let nextTraversedDistance = cumulativeDistances[index]
            let segmentDistance = nextTraversedDistance - traversedDistance

            if targetDistance <= nextTraversedDistance {
                let segmentProgress = segmentDistance > 0
                ? (targetDistance - traversedDistance) / segmentDistance
                : 0
                
                return interpolateCoordinate(
                    from: coordinates[index - 1],
                    to: coordinates[index],
                    progress: segmentProgress
                )
            }
        }
        
        return last
    }

    private func interpolateCoordinate(
        from start: CLLocationCoordinate2D,
        to end: CLLocationCoordinate2D,
        progress: Double
    ) -> CLLocationCoordinate2D {
        let latitude = start.latitude + (end.latitude - start.latitude) * progress
        let longitude = start.longitude + (end.longitude - start.longitude) * progress
        return CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
    
    private func createAnnotationsAndOverlays(for itinerary: Itinerary) -> (annotations: [StopAnnotation], overlays: [RouteOverlay]) {
        var annotations: [StopAnnotation] = []
        var overlays: [RouteOverlay] = []
        
        if let firstLeg = itinerary.legs.first {
            let firstLegColor = getLegColor(firstLeg)
            annotations.append(StopAnnotation(place: firstLeg.from, color: firstLegColor, isTerminal: true))
        }
        
        for (index, leg) in itinerary.legs.enumerated() {
            let legColor = getLegColor(leg)
            
            if let intermediateStops = leg.intermediateStops {
                for stop in intermediateStops {
                    annotations.append(StopAnnotation(place: stop, color: legColor, isIntermediate: true))
                }
            }
            
            let isLastLeg = index == itinerary.legs.count - 1
            let isTransferPoint = !isLastLeg && itinerary.legs[index + 1].mode != leg.mode
            
            let annotationColor = (!isLastLeg && leg.mode == .walk) ? getLegColor(itinerary.legs[index + 1]) : legColor
            

            var terminalPlace = !isLastLeg ? itinerary.legs[index + 1].from : leg.to
            if isLastLeg, terminalPlace.name == "END", let destinationName {
                terminalPlace.name = destinationName
            }

            annotations.append(StopAnnotation(
                place: terminalPlace,
                color: annotationColor,
                isTerminal: isLastLeg || isTransferPoint,
                isIntermediate: !isLastLeg && !isTransferPoint
            ))
            
            if let overlay = createRouteOverlay(for: leg, withColor: legColor) {
                overlays.append(overlay)
            }
        }
        
        return (removeDuplicateAnnotations(annotations), overlays)
    }

    private func removeDuplicateAnnotations(_ annotations: [StopAnnotation]) -> [StopAnnotation] {
        var uniqueAnnotations: [StopAnnotation] = []
        var seenCoordinates: [String: Int] = [:]
        
        for annotation in annotations {
            let key = "\(annotation.coordinate.latitude),\(annotation.coordinate.longitude)"
            
            if let existingIndex = seenCoordinates[key] {
                if annotation.isTerminal && !uniqueAnnotations[existingIndex].isTerminal {
                    uniqueAnnotations[existingIndex] = annotation
                }
            } else {
                uniqueAnnotations.append(annotation)
                seenCoordinates[key] = uniqueAnnotations.count - 1
            }
        }
        
        return uniqueAnnotations
    }

    
    private func createRouteOverlay(for leg: Leg, withColor color: Color) -> RouteOverlay? {
        let polyline = Polyline(encodedPolyline: leg.legGeometry.points, precision: 1e6)
        
        guard let coordinates = polyline.coordinates, !coordinates.isEmpty else { return nil }

        let simplifiedCoordinates = reduceCoordinatesIfNeeded(
            coordinates,
            maxPoints: maxRouteOverlayPointsPerLeg
        )

        let legId = getLegIdentifier(leg)
        return RouteOverlay(id: legId, coordinates: simplifiedCoordinates, color: color)
    }
    
    private func calculateMapPosition() {
        guard !mapAnnotations.isEmpty else { return }
        
        let mapRect = mapAnnotations.reduce(into: MKMapRect.null) { rect, annotation in
            let point = MKMapPoint(annotation.coordinate)
            let pointRect = MKMapRect(x: point.x, y: point.y, width: 0.1, height: 0.1)
            rect = rect.union(pointRect)
        }.union(
            routeOverlays.reduce(into: MKMapRect.null) { rect, overlay in
                overlay.coordinates.forEach {
                    let point = MKMapPoint($0)
                    let pointRect = MKMapRect(x: point.x, y: point.y, width: 0.1, height: 0.1)
                    rect = rect.union(pointRect)
                }
            }
        )
        
        let padding = 0.2
        position = .rect(mapRect.insetBy(dx: -mapRect.width * padding/2, dy: -mapRect.height * padding/2))
    }
}

func getLegColor(_ leg: Leg, brightIt: Bool = false) -> Color {
    switch leg.mode {
    case .walk:
        return .blue
    case .bike, .car:
        return .gray
    default:
        let baseColor: Color

        if let routeName = leg.routeShortName {
            let isTrainDetected = routeName.hasPrefix("RL") || routeName.hasPrefix("IR") ||
                                routeName.hasPrefix("RE") || routeName.hasPrefix("IC") || routeName == "R"
            baseColor = LineColors.resolve(
                line: routeName,
                agency: leg.agencyId,
                isSquared: leg.mode.usesSquaredPill || isTrainDetected
            ).color
        } else {
            baseColor = leg.mode.usesSquaredPill ? Color(hex: "EA0706") : .accent
        }

        if brightIt && isDarkColor(baseColor) {
            return lightenColor(baseColor)
        }
        return baseColor
    }
}

func isDarkColor(_ color: Color) -> Bool {
    let uiColor = UIColor(color)
    var red: CGFloat = 0
    var green: CGFloat = 0
    var blue: CGFloat = 0
    var alpha: CGFloat = 0
    
    uiColor.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
    
    // ITU-R BT.709, https://stackoverflow.com/a/596243
    let luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    return luminance < 0.4
}
    
func lightenColor(_ color: Color, by factor: Double = 0.25) -> Color {
    let uiColor = UIColor(color)
    var hue: CGFloat = 0
    var saturation: CGFloat = 0
    var brightness: CGFloat = 0
    var alpha: CGFloat = 0
    
    uiColor.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: &alpha)
    
    let newBrightness = min(1.0, brightness + CGFloat(factor))
    let newSaturation = max(0.3, saturation * 0.8)
    
    return Color(hue: Double(hue), saturation: Double(newSaturation), brightness: Double(newBrightness))
}
