//
//  ItineraryViewModel.swift
//  Lux
//
//  Created by Constantin Clerc on 23.04.2025.
//

import SwiftUI
import MapKit
import LuxCom
import LuxComHAFAS
import Polyline

@MainActor
final class ItineraryViewModel: ObservableObject {
    @Published var tripId: String
    private let zoomThreshold: CLLocationDistance = 50000
    private var legKeyFrames: [String: [VehicleVisualisation.KeyFrame]] = [:]
    private var vehicleUpdateTask: Task<Void, Never>?
    private var itineraryRefreshTask: Task<Void, Never>?
    
    private var shouldStop = false
    
    @Published var itinerary: Itinerary?
    @Published var position: MapCameraPosition = .automatic
    @Published var mapAnnotations: [StopAnnotation] = []
    @Published var routeOverlays: [RouteOverlay] = []
    @Published var showingIntermediateStops: Bool = true
    @Published var vehicleAnnotations: [VehicleAnnotation] = []
    @Published var isLoading: Bool = true
    @Published var error: String?
    @Published var walkingDirections: [String: [MKRoute.Step]] = [:]
    @ObservedObject var settings = Settings.shared
        
    init(tripId: String) {
        self.tripId = tripId
    }
    
    convenience init(itinerary: Itinerary) {
        self.init(tripId: "")
        self.itinerary = itinerary
    }
        
    func switchToTrip(tripId: String) async {
        guard tripId != self.tripId else { return }
        
        stopAllTasks()
        
        self.vehicleAnnotations = []
        self.tripId = tripId
        self.itinerary = nil
        self.mapAnnotations = []
        self.routeOverlays = []
        self.walkingDirections = [:]
        self.legKeyFrames = [:]
        self.error = nil
        self.shouldStop = false
        
        await loadItinerary()
    }
    
    func stopAllTasks() {
        shouldStop = true
        stopItineraryRefresh()
        stopVehicleUpdates()
    }
    
    func loadItinerary() async {
        guard !shouldStop else { return }
        
        if itinerary != nil {
            await processItinerary()
            await refreshItinerary(dontActuallyFetch: true)
            isLoading = false
            startItineraryRefresh()
            return
        }
        
        isLoading = true
        error = nil
        
        do {
            if settings.dataSource == .luxCom {
                itinerary = try await getTrip(tripId: tripId)
            }
            else {
                itinerary = try await citaGetTrip(tripId: tripId)
            }
            if itinerary != nil {
                await processItinerary()
                startItineraryRefresh()
            } else {
                error = "No itinerary data found"
            }
        } catch {
            self.error = error.localizedDescription
        }
        
        isLoading = false
    }
    
    // MKDirections
    func fetchWalkingDirections(for leg: Leg) async {
        guard leg.mode == .walk else { return }
        
        let legId = getLegIdentifier(leg)
        
        if walkingDirections[legId] != nil {
            return
        }
        
        let request = MKDirections.Request()
        
        let sourceCoordinate = CLLocationCoordinate2D(latitude: leg.from.lat, longitude: leg.from.lon)
        let destinationCoordinate = CLLocationCoordinate2D(latitude: leg.to.lat, longitude: leg.to.lon)
        
        request.source = MKMapItem(placemark: MKPlacemark(coordinate: sourceCoordinate))
        request.destination = MKMapItem(placemark: MKPlacemark(coordinate: destinationCoordinate))
        request.transportType = .walking
        
        let directions = MKDirections(request: request)
        
        do {
            let response = try await directions.calculate()
            if let route = response.routes.first {
                var steps = route.steps
                
                if steps.count > 2 {
                    // those remove head to/arrive to generated by mkdirections
                    steps.removeFirst()
                    steps.removeLast()
                }
                
                await MainActor.run {
                    walkingDirections[legId] = steps
                }
            }
        } catch {
            print("failed to calculate walking directions for leg \(legId) !!! \(error)")
        }
    }
        
    private func startItineraryRefresh() {
        guard !tripId.isEmpty && !shouldStop else { return }
        
        stopItineraryRefresh()
        
        itineraryRefreshTask = Task {
            while !Task.isCancelled && !shouldStop {
                try? await Task.sleep(for: .seconds(10))
                
                guard !Task.isCancelled && !shouldStop else { break }
                
                await refreshItinerary()
            }
        }
    }
    
    private func stopItineraryRefresh() {
        itineraryRefreshTask?.cancel()
        itineraryRefreshTask = nil
    }
    
    private func refreshItinerary(dontActuallyFetch: Bool = false) async {
        guard !tripId.isEmpty && !shouldStop else { return }
        
        do {
            if !dontActuallyFetch {
                if settings.dataSource == .luxCom {
                    let newItinerary = try await getTrip(tripId: tripId)
                    itinerary = newItinerary
                }
                else {
                    let newItinerary = try await citaGetTrip(tripId: tripId)
                    itinerary = newItinerary
                }
            }
            else {
                itinerary = itinerary
            }
            
            await processItinerary(shouldCalculateMapPosition: false)
        } catch {
            print("failed to refresh! \(error.localizedDescription)")
        }
    }
    
    func updateZoomLevel(distance: CLLocationDistance) {
        showingIntermediateStops = distance < zoomThreshold
    }
    
    private func processItinerary(shouldCalculateMapPosition: Bool = true) async {
        guard let itinerary = itinerary, !shouldStop else {
            error = "Missing itinerary data"
            return
        }
                
        if shouldCalculateMapPosition {
            let (annotations, overlays) = createAnnotationsAndOverlays(for: itinerary)
            mapAnnotations = annotations
            routeOverlays = overlays
            calculateMapPosition()
        }
        
        if settings.fetchWalkingDirectionsUsingMKDirections {
            await fetchWalkingDirectionsForAllLegs(itinerary.legs)
        }
        
        prepareVehicleKeyframes(for: itinerary.legs)
        
        startVehicleUpdates()
    }
    
    private func fetchWalkingDirectionsForAllLegs(_ legs: [Leg]) async {
        await withTaskGroup(of: Void.self) { group in
            for leg in legs where leg.mode == .walk {
                group.addTask {
                    await self.fetchWalkingDirections(for: leg)
                }
            }
        }
    }
    
    private func prepareVehicleKeyframes(for legs: [Leg]) {
        guard !shouldStop else { return }
        
        legKeyFrames.removeAll()
        
        for leg in legs where leg.mode != .walk && leg.mode != .bike {
            let legId = getLegIdentifier(leg)
            let keyFrames = VehicleVisualisation.calculateKeyFrames(for: leg, polylineString: leg.legGeometry.points, precision: 1e6)
            legKeyFrames[legId] = keyFrames
        }
    }
    
    func getLegIdentifier(_ leg: Leg) -> String {
        "\(leg.routeShortName ?? "")_\(leg.headsign ?? "")_\(leg.startTime.timeIntervalSince1970)"
    }
    
    private func startVehicleUpdates() {
        guard !shouldStop else { return }
        
        stopVehicleUpdates()
        
        vehicleUpdateTask = Task {
            while !Task.isCancelled && !shouldStop {
                updateVehiclePositions()
                try? await Task.sleep(for: .seconds(2))
            }
        }
    }

    deinit {
        shouldStop = true
        vehicleUpdateTask?.cancel()
        itineraryRefreshTask?.cancel()
        vehicleUpdateTask = nil
        itineraryRefreshTask = nil
    }
    
    private func stopVehicleUpdates() {
        vehicleUpdateTask?.cancel()
        vehicleUpdateTask = nil
    }

    private func updateVehiclePositions() {
        guard let itinerary = itinerary, !shouldStop else { return }
        
        let currentTime = Date()
        let currentTimeInterval = currentTime.timeIntervalSince1970
        
        let newVehicleAnnotations = itinerary.legs.compactMap { leg -> VehicleAnnotation? in
            guard leg.mode != .walk && leg.mode != .bike else { return nil }
            
            guard leg.startTime <= currentTime && leg.endTime >= currentTime else { return nil }
            
            let legId = getLegIdentifier(leg)
            
            guard let keyFrames = legKeyFrames[legId],
                  let position = VehicleVisualisation.interpolatePosition(
                    at: currentTimeInterval,
                    using: keyFrames
                  ) else { return nil }
            
            return VehicleAnnotation(
                id: legId,
                coordinate: position,
                routeShortName: leg.routeShortName,
                color: getLegColor(leg)
            )
        }
        
        withAnimation(.easeInOut(duration: 0.5)) {
            vehicleAnnotations = newVehicleAnnotations
        }
    }
    
    private func createAnnotationsAndOverlays(for itinerary: Itinerary) -> (annotations: [StopAnnotation], overlays: [RouteOverlay]) {
        var annotations: [StopAnnotation] = []
        var overlays: [RouteOverlay] = []
        
        if let firstLeg = itinerary.legs.first {
            let firstLegColor = getLegColor(firstLeg)
            annotations.append(StopAnnotation(place: firstLeg.from, color: firstLegColor, isTerminal: true))
        }
        
        for (index, leg) in itinerary.legs.enumerated() {
            let legColor = getLegColor(leg)
            
            if let intermediateStops = leg.intermediateStops {
                for stop in intermediateStops {
                    annotations.append(StopAnnotation(place: stop, color: legColor, isIntermediate: true))
                }
            }
            
            let isLastLeg = index == itinerary.legs.count - 1
            let isTransferPoint = !isLastLeg && itinerary.legs[index + 1].mode != leg.mode
            
            let annotationColor = (!isLastLeg && leg.mode == .walk) ? getLegColor(itinerary.legs[index + 1]) : legColor
            
            annotations.append(StopAnnotation(
                place: !isLastLeg ? itinerary.legs[index + 1].from : leg.to,
                color: annotationColor,
                isTerminal: isLastLeg || isTransferPoint,
                isIntermediate: !isLastLeg && !isTransferPoint
            ))
            
            if let overlay = createRouteOverlay(for: leg, withColor: legColor) {
                overlays.append(overlay)
            }
        }
        
        return (removeDuplicateAnnotations(annotations), overlays)
    }

    private func removeDuplicateAnnotations(_ annotations: [StopAnnotation]) -> [StopAnnotation] {
        var uniqueAnnotations: [StopAnnotation] = []
        var seenCoordinates: [String: Int] = [:]
        
        for annotation in annotations {
            let key = "\(annotation.coordinate.latitude),\(annotation.coordinate.longitude)"
            
            if let existingIndex = seenCoordinates[key] {
                if annotation.isTerminal && !uniqueAnnotations[existingIndex].isTerminal {
                    uniqueAnnotations[existingIndex] = annotation
                }
            } else {
                uniqueAnnotations.append(annotation)
                seenCoordinates[key] = uniqueAnnotations.count - 1
            }
        }
        
        return uniqueAnnotations
    }

    
    private func createRouteOverlay(for leg: Leg, withColor color: Color) -> RouteOverlay? {
        let polyline = Polyline(encodedPolyline: leg.legGeometry.points, precision: 1e6)
        
        guard let coordinates = polyline.coordinates, !coordinates.isEmpty else { return nil }
        
        return RouteOverlay(coordinates: coordinates, color: color)
    }
    
    private func calculateMapPosition() {
        guard !mapAnnotations.isEmpty else { return }
        
        let mapRect = mapAnnotations.reduce(into: MKMapRect.null) { rect, annotation in
            let point = MKMapPoint(annotation.coordinate)
            let pointRect = MKMapRect(x: point.x, y: point.y, width: 0.1, height: 0.1)
            rect = rect.union(pointRect)
        }.union(
            routeOverlays.reduce(into: MKMapRect.null) { rect, overlay in
                overlay.coordinates.forEach {
                    let point = MKMapPoint($0)
                    let pointRect = MKMapRect(x: point.x, y: point.y, width: 0.1, height: 0.1)
                    rect = rect.union(pointRect)
                }
            }
        )
        
        let padding = 0.2
        position = .rect(mapRect.insetBy(dx: -mapRect.width * padding/2, dy: -mapRect.height * padding/2))
    }
}

func getLegColor(_ leg: Leg, brightIt: Bool = false) -> Color {
    switch leg.mode {
    case .walk:
        return .blue
    case .bike, .car:
        return .gray
    default:
        var baseColor: Color
        
        if let routeName = leg.routeShortName {
            if let color = LineColors.color(for: routeName) {
                baseColor = color
            } else {
                let isTrainDetected = routeName.hasPrefix("RL") || routeName.hasPrefix("IR") ||
                                    routeName.hasPrefix("RE") || routeName.hasPrefix("IC") || routeName == "R"
                
                let squaredModes: Set<TransportationMode> = [
                    .regionalRail, .ferry, .rail, .highSpeedRail,
                    .longDistance, .metro, .nightRail, .regionalFastRail
                ]
                
                let isSquared = squaredModes.contains(leg.mode) || isTrainDetected
                if isSquared {
                    baseColor = Color(hex: "EA0706")
                } else {
                    baseColor = Color.accent
                }
            }
        } else {
            if leg.mode == .rail || leg.mode == .highSpeedRail ||
               leg.mode == .regionalRail || leg.mode == .regionalFastRail {
                baseColor = Color(hex: "EA0706")
            } else {
                baseColor = .accent
            }
        }
        
        if brightIt && isDarkColor(baseColor) {
            return lightenColor(baseColor)
        }
        return baseColor
    }
}

func isDarkColor(_ color: Color) -> Bool {
    let uiColor = UIColor(color)
    var red: CGFloat = 0
    var green: CGFloat = 0
    var blue: CGFloat = 0
    var alpha: CGFloat = 0
    
    uiColor.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
    
    // ITU-R BT.709, https://stackoverflow.com/a/596243
    let luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    return luminance < 0.4
}
    
func lightenColor(_ color: Color, by factor: Double = 0.25) -> Color {
    let uiColor = UIColor(color)
    var hue: CGFloat = 0
    var saturation: CGFloat = 0
    var brightness: CGFloat = 0
    var alpha: CGFloat = 0
    
    uiColor.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: &alpha)
    
    let newBrightness = min(1.0, brightness + CGFloat(factor))
    let newSaturation = max(0.3, saturation * 0.8)
    
    return Color(hue: Double(hue), saturation: Double(newSaturation), brightness: Double(newBrightness))
}
