//
//  SymbolLexicon.swift
//  Lux
//
//  Created by Constantin Clerc on 23.08.2026.
//

import Foundation

enum SymbolLexicon {
    static let translations: [String: [String]] = [
        // MARK: Transport
        "train": ["train", "tram"],
        "tram": ["tram"],
        "bus": ["bus"],
        "car": ["bus"],
        "metro": ["tram", "train"],
        "rer": ["train"],
        "gare": ["train", "tram"],
        "arret": ["bus", "stop"],
        "station": ["train", "bus"],
        "quai": ["train"],
        "voie": ["train", "road"],
        "rail": ["train"],
        "ligne": ["line", "road"],
        "voiture": ["car"],
        "auto": ["car"],
        "automobile": ["car"],
        "taxi": ["car"],
        "camion": ["truck"],
        "camionnette": ["truck"],
        "moto": ["motorcycle", "scooter"],
        "scooter": ["scooter", "moped"],
        "velo": ["bicycle"],
        "bicyclette": ["bicycle"],
        "trottinette": ["scooter"],
        "bateau": ["ferry", "sailboat"],
        "ferry": ["ferry"],
        "navette": ["bus"],
        "avion": ["airplane"],
        "aeroport": ["airplane"],
        "vol": ["airplane"],
        "funiculaire": ["cablecar"],
        "telepherique": ["cablecar"],
        "teleferique": ["cablecar"],
        "remontee": ["cablecar"],
        "tunnel": ["road"],
        "pont": ["road"],
        "route": ["road"],
        "rue": ["road"],
        "autoroute": ["road"],
        "carrefour": ["road"],
        "peage": ["road"],
        "parking": ["parkingsign", "car"],
        "essence": ["fuelpump"],
        "carburant": ["fuelpump"],
        "recharge": ["bolt", "battery"],
        "borne": ["bolt"],
        "trajet": ["map", "arrow.triangle.turn.up.right.diamond"],
        "itineraire": ["map", "signpost"],
        "correspondance": ["arrow.triangle.swap"],
        "direction": ["signpost", "arrow"],
        "panneau": ["signpost"],
        "boussole": ["compass"],
        "carte": ["map"],
        "plan": ["map"],
        "position": ["location"],
        "localisation": ["location"],
        "distance": ["ruler"],
        "vitesse": ["speedometer"],
        "retard": ["clock.badge.exclamationmark"],
        "depart": ["arrow.up.forward"],
        "arrivee": ["arrow.down.forward"],
        "billet": ["ticket"],
        "ticket": ["ticket"],
        "abonnement": ["ticket", "creditcard"],
        "horaire": ["clock", "calendar"],
        "bagage": ["suitcase"],
        "valise": ["suitcase"],
        "sac": ["bag"],
        "poussette": ["stroller"],
        "marche": ["figure.walk"],
        "pieton": ["figure.walk"],
        "course": ["figure.run"],

        // MARK: Lieux
        "maison": ["house"],
        "domicile": ["house"],
        "chez": ["house"],
        "appartement": ["building"],
        "immeuble": ["building"],
        "batiment": ["building"],
        "bureau": ["briefcase", "building"],
        "travail": ["briefcase"],
        "boulot": ["briefcase"],
        "ecole": ["graduationcap", "book"],
        "universite": ["graduationcap", "building.columns"],
        "cours": ["graduationcap", "book"],
        "hopital": ["cross", "stethoscope"],
        "medecin": ["stethoscope"],
        "dentiste": ["mouth"],
        "pharmacie": ["cross", "pills"],
        "magasin": ["storefront", "bag"],
        "boutique": ["storefront", "bag"],
        "supermarche": ["cart"],
        "commerce": ["storefront"],
        "restaurant": ["fork.knife"],
        "cafe": ["cup.and.saucer"],
        "bar": ["wineglass"],
        "hotel": ["bed.double"],
        "banque": ["building.columns", "creditcard"],
        "poste": ["envelope"],
        "eglise": ["building.columns"],
        "musee": ["building.columns"],
        "theatre": ["theatermasks"],
        "cinema": ["film"],
        "bibliotheque": ["books.vertical"],
        "parc": ["tree", "leaf"],
        "jardin": ["leaf", "tree"],
        "plage": ["beach.umbrella"],
        "montagne": ["mountain.2"],
        "foret": ["tree"],
        "lac": ["water.waves"],
        "riviere": ["water.waves"],
        "stade": ["sportscourt"],
        "piscine": ["figure.pool.swim", "water.waves"],
        "salle": ["figure.strengthtraining.traditional"],
        "sport": ["figure.run", "sportscourt"],
        "gym": ["dumbbell"],
        "usine": ["building.2"],
        "chantier": ["hammer"],
        "ferme": ["tree"],
        "place": ["mappin"],
        "ville": ["building.2"],
        "village": ["house"],
        "quartier": ["building.2"],

        // MARK: Personnes
        "personne": ["person"],
        "gens": ["person.3"],
        "groupe": ["person.3"],
        "famille": ["figure.2.and.child.holdinghands"],
        "enfant": ["figure.child"],
        "bebe": ["stroller"],
        "homme": ["person"],
        "femme": ["person"],
        "ami": ["person.2"],
        "contact": ["person.crop.circle"],
        "utilisateur": ["person.crop.circle"],
        "compte": ["person.crop.circle"],
        "profil": ["person.crop.circle"],
        "equipe": ["person.3"],
        "rendez": ["calendar"],
        "reunion": ["person.3", "calendar"],

        // MARK: Corps et santé
        "coeur": ["heart"],
        "cerveau": ["brain"],
        "oeil": ["eye"],
        "oreille": ["ear"],
        "bouche": ["mouth"],
        "main": ["hand.raised"],
        "doigt": ["hand.point.up"],
        "pied": ["shoeprints.fill", "figure.walk"],
        "dent": ["mouth"],
        "os": ["figure.walk"],
        "sante": ["heart.text.square", "cross"],
        "medicament": ["pills"],
        "pilule": ["pills"],
        "seringue": ["syringe"],
        "pansement": ["bandage"],
        "urgence": ["cross.case", "exclamationmark.triangle"],
        "sommeil": ["bed.double", "moon.zzz"],
        "poids": ["scalemass"],

        // MARK: Nature et météo
        "soleil": ["sun.max"],
        "lune": ["moon"],
        "etoile": ["star"],
        "nuage": ["cloud"],
        "pluie": ["cloud.rain"],
        "neige": ["snowflake", "cloud.snow"],
        "flocon": ["snowflake"],
        "vent": ["wind"],
        "orage": ["cloud.bolt"],
        "eclair": ["bolt"],
        "foudre": ["bolt"],
        "brouillard": ["cloud.fog"],
        "temperature": ["thermometer"],
        "thermometre": ["thermometer"],
        "chaud": ["thermometer.sun", "flame"],
        "froid": ["thermometer.snowflake", "snowflake"],
        "goutte": ["drop"],
        "eau": ["drop", "water.waves"],
        "feu": ["flame"],
        "flamme": ["flame"],
        "terre": ["globe"],
        "globe": ["globe"],
        "monde": ["globe"],
        "planete": ["globe"],
        "arbre": ["tree"],
        "feuille": ["leaf"],
        "fleur": ["camera.macro"],
        "plante": ["leaf"],
        "vague": ["water.waves"],
        "mer": ["water.waves"],

        // MARK: Animaux
        "chien": ["dog"],
        "chat": ["cat"],
        "oiseau": ["bird"],
        "poisson": ["fish"],
        "lapin": ["hare"],
        "tortue": ["tortoise"],
        "papillon": ["camera.macro"],
        "fourmi": ["ant"],
        "abeille": ["ant"],
        "ours": ["teddybear"],
        "souris": ["computermouse"],
        "cheval": ["pawprint"],
        "vache": ["pawprint"],
        "patte": ["pawprint"],

        // MARK: Nourriture
        "the": ["mug", "cup.and.saucer"],
        "tasse": ["cup.and.saucer"],
        "verre": ["wineglass"],
        "bouteille": ["waterbottle"],
        "biere": ["wineglass"],
        "vin": ["wineglass"],
        "pizza": ["fork.knife"],
        "pain": ["fork.knife"],
        "gateau": ["birthday.cake"],
        "glace": ["snowflake"],
        "fruit": ["carrot"],
        "pomme": ["applelogo", "carrot"],
        "carotte": ["carrot"],
        "viande": ["fork.knife"],
        "fourchette": ["fork.knife"],
        "couteau": ["fork.knife"],
        "assiette": ["fork.knife"],
        "panier": ["basket"],
        "chariot": ["cart"],
        "courses": ["cart", "basket"],
        "repas": ["fork.knife"],

        // MARK: Objets
        "cle": ["key"],
        "clef": ["key"],
        "cadenas": ["lock"],
        "verrou": ["lock"],
        "serrure": ["lock"],
        "boite": ["shippingbox"],
        "carton": ["shippingbox"],
        "colis": ["shippingbox"],
        "cadeau": ["gift"],
        "livre": ["book"],
        "cahier": ["book.closed", "note.text"],
        "crayon": ["pencil"],
        "stylo": ["pencil", "pencil.and.outline"],
        "ciseaux": ["scissors"],
        "regle": ["ruler"],
        "marteau": ["hammer"],
        "tournevis": ["screwdriver"],
        "outil": ["wrench.and.screwdriver"],
        "ampoule": ["lightbulb"],
        "lampe": ["lamp.desk", "lightbulb"],
        "bougie": ["flame"],
        "batterie": ["battery.100"],
        "pile": ["battery.100"],
        "prise": ["powerplug"],
        "cable": ["cable.connector"],
        "casque": ["headphones"],
        "ecouteur": ["headphones", "airpods"],
        "haut": ["speaker.wave.2", "arrow.up"],
        "parleur": ["speaker.wave.2"],
        "micro": ["mic"],
        "appareil": ["camera"],
        "photo": ["photo", "camera"],
        "video": ["video"],
        "film": ["film"],
        "musique": ["music.note"],
        "note": ["music.note", "note.text"],
        "guitare": ["guitars"],
        "piano": ["pianokeys"],
        "radio": ["radio"],
        "television": ["tv"],
        "tele": ["tv"],
        "ecran": ["display"],
        "ordinateur": ["desktopcomputer", "laptopcomputer"],
        "portable": ["iphone", "laptopcomputer"],
        "telephone": ["phone", "iphone"],
        "tablette": ["ipad"],
        "montre": ["clock", "stopwatch"],
        "horloge": ["clock"],
        "reveil": ["alarm"],
        "minuteur": ["timer"],
        "chronometre": ["stopwatch"],
        "sablier": ["hourglass"],
        "calendrier": ["calendar"],
        "agenda": ["calendar"],
        "journal": ["newspaper"],
        "document": ["doc"],
        "fichier": ["doc"],
        "dossier": ["folder"],
        "papier": ["doc"],
        "enveloppe": ["envelope"],
        "lettre": ["envelope"],
        "courrier": ["envelope"],
        "message": ["message"],
        "discussion": ["bubble.left.and.bubble.right"],
        "conversation": ["bubble.left.and.bubble.right"],
        "appel": ["phone"],
        "sonnerie": ["bell"],
        "cloche": ["bell"],
        "alarme": ["alarm", "bell"],
        "notification": ["bell"],
        "parapluie": ["umbrella"],
        "lunettes": ["eyeglasses"],
        "chapeau": ["graduationcap"],
        "chaussure": ["shoeprints.fill"],
        "vetement": ["tshirt"],

        // MARK: Argent
        "euro": ["eurosign"],
        "franc": ["francsign"],
        "dollar": ["dollarsign"],
        "argent": ["banknote", "creditcard"],
        "paiement": ["creditcard"],
        "payer": ["creditcard"],
        "credit": ["creditcard"],
        "portefeuille": ["wallet.pass"],
        "monnaie": ["banknote"],
        "prix": ["tag"],
        "tarif": ["tag"],
        "reduction": ["tag", "percent"],
        "achat": ["cart", "bag"],
        "recu": ["receipt", "doc.text"],
        "facture": ["receipt", "doc.text"],
        "pourcent": ["percent"],
        "scanner": ["qrcode.viewfinder", "barcode.viewfinder"],
        "code": ["qrcode"],

        // MARK: Temps
        "heure": ["clock"],
        "minute": ["clock"],
        "temps": ["clock"],
        "date": ["calendar"],
        "jour": ["calendar", "sun.max"],
        "semaine": ["calendar"],
        "mois": ["calendar"],
        "annee": ["calendar"],
        "matin": ["sunrise"],
        "soir": ["sunset"],
        "nuit": ["moon.stars"],
        "midi": ["sun.max"],
        "historique": ["clock.arrow.circlepath"],
        "recent": ["clock.arrow.circlepath"],

        // MARK: Interface et actions
        "ajouter": ["plus"],
        "supprimer": ["trash", "minus"],
        "effacer": ["eraser", "trash"],
        "corbeille": ["trash"],
        "poubelle": ["trash"],
        "modifier": ["pencil", "slider.horizontal.3"],
        "editer": ["pencil"],
        "ecrire": ["square.and.pencil"],
        "copier": ["doc.on.doc"],
        "coller": ["doc.on.clipboard"],
        "couper": ["scissors"],
        "partager": ["square.and.arrow.up"],
        "envoyer": ["paperplane"],
        "recevoir": ["tray.and.arrow.down"],
        "telecharger": ["arrow.down.circle"],
        "importer": ["square.and.arrow.down"],
        "exporter": ["square.and.arrow.up"],
        "enregistrer": ["square.and.arrow.down"],
        "sauvegarder": ["externaldrive"],
        "imprimer": ["printer"],
        "rechercher": ["magnifyingglass"],
        "recherche": ["magnifyingglass"],
        "loupe": ["magnifyingglass"],
        "filtre": ["line.3.horizontal.decrease"],
        "trier": ["arrow.up.arrow.down"],
        "parametre": ["gearshape"],
        "reglage": ["gearshape", "slider.horizontal.3"],
        "engrenage": ["gearshape"],
        "roue": ["gearshape"],
        "curseur": ["slider.horizontal.3"],
        "bouton": ["button.horizontal"],
        "menu": ["line.3.horizontal"],
        "liste": ["list.bullet"],
        "grille": ["square.grid.2x2"],
        "tableau": ["tablecells"],
        "graphique": ["chart.bar"],
        "statistique": ["chart.bar"],
        "diagramme": ["chart.pie"],
        "fleche": ["arrow"],
        "bas": ["arrow.down"],
        "gauche": ["arrow.left"],
        "droite": ["arrow.right"],
        "retour": ["arrow.uturn.backward"],
        "avant": ["arrow.forward"],
        "arriere": ["arrow.backward"],
        "rafraichir": ["arrow.clockwise"],
        "actualiser": ["arrow.clockwise"],
        "recharger": ["arrow.clockwise"],
        "repeter": ["repeat"],
        "aleatoire": ["shuffle"],
        "lecture": ["play"],
        "lire": ["play"],
        "pause": ["pause"],
        "arreter": ["stop"],
        "suivant": ["forward.end"],
        "precedent": ["backward.end"],
        "volume": ["speaker.wave.2"],
        "son": ["speaker.wave.2"],
        "muet": ["speaker.slash"],
        "verrouiller": ["lock"],
        "deverrouiller": ["lock.open"],
        "masquer": ["eye.slash"],
        "afficher": ["eye"],
        "coche": ["checkmark"],
        "valider": ["checkmark.circle"],
        "croix": ["xmark"],
        "annuler": ["xmark.circle", "arrow.uturn.backward"],
        "fermer": ["xmark"],
        "ouvrir": ["arrow.up.forward.app"],
        "question": ["questionmark.circle"],
        "aide": ["questionmark.circle"],
        "info": ["info.circle"],
        "information": ["info.circle"],
        "avertissement": ["exclamationmark.triangle"],
        "attention": ["exclamationmark.triangle"],
        "erreur": ["exclamationmark.octagon"],
        "danger": ["exclamationmark.triangle"],
        "interdit": ["nosign"],
        "favori": ["star", "heart"],
        "signet": ["bookmark"],
        "epingle": ["pin"],
        "punaise": ["pin"],
        "drapeau": ["flag"],
        "etiquette": ["tag"],
        "archive": ["archivebox"],
        "synchroniser": ["arrow.triangle.2.circlepath"],
        "reseau": ["network"],
        "antenne": ["antenna.radiowaves.left.and.right"],
        "signal": ["antenna.radiowaves.left.and.right"],
        "energie": ["bolt"],
        "sombre": ["moon"],
        "clair": ["sun.max"],
        "luminosite": ["sun.max"],
        "couleur": ["paintpalette"],
        "palette": ["paintpalette"],
        "pinceau": ["paintbrush"],
        "peinture": ["paintbrush"],
        "texte": ["textformat"],
        "gras": ["bold"],
        "italique": ["italic"],
        "souligne": ["underline"],
        "langue": ["globe", "character.bubble"],
        "traduction": ["character.bubble", "globe"],
        "securite": ["lock.shield"],
        "bouclier": ["shield"],
        "protection": ["shield"],
        "confidentialite": ["hand.raised", "lock.shield"],
        "prive": ["lock"],
        "empreinte": ["lock.shield", "hand.raised"],
        "visage": ["face.smiling", "person.crop.circle"],
        "sourire": ["face.smiling"],
        "jeu": ["gamecontroller"],
        "manette": ["gamecontroller"],
        "carre": ["square"],
        "rond": ["circle"],
        "cercle": ["circle"],
        "triangle": ["triangle"],
        "losange": ["diamond"],
        "forme": ["square.on.circle"],
        "plus": ["plus"],
        "moins": ["minus"],
        "egal": ["equal"],
        "nombre": ["number"],
        "chiffre": ["number"],
        "calcul": ["plus.forwardslash.minus"],
        "disque": ["externaldrive", "opticaldiscdrive"],
        "serveur": ["server.rack"],
        "base": ["cylinder.split.1x2"],

        // MARK: Famille et proches
        "papa": ["person", "figure.2.and.child.holdinghands"],
        "maman": ["person", "figure.2.and.child.holdinghands"],
        "parent": ["figure.2.and.child.holdinghands", "person.2"],
        "mamie": ["person", "figure.2.and.child.holdinghands"],
        "papy": ["person", "figure.2.and.child.holdinghands"],
        "papi": ["person", "figure.2.and.child.holdinghands"],
        "copine": ["heart", "person.2"],
        "copain": ["heart", "person.2"],
        "cheri": ["heart"],
        "amoureux": ["heart"],
        "nounou": ["figure.child", "stroller"],
        "creche": ["figure.child", "stroller"],
        "garderie": ["figure.child", "stroller"],
        "voisin": ["house", "person.2"],

        // MARK: Familier et abréviations
        "taf": ["briefcase"],
        "resto": ["fork.knife"],
        "cine": ["film"],
        "appart": ["building", "house"],
        "uni": ["graduationcap", "building.columns"],
        "fac": ["graduationcap", "building.columns"],
        "veto": ["pawprint", "stethoscope"],
        "perso": ["person.crop.circle"],
        "coiffeur": ["scissors"],
        "chalet": ["house.lodge"],

        // MARK: Anglais courant
        "home": ["house"],
        "work": ["briefcase"],
        "school": ["graduationcap"],
        "office": ["briefcase", "building"],
        "shop": ["bag", "storefront"],
        "food": ["fork.knife"],

        // MARK: Rendez-vous et sorties
        "rdv": ["calendar", "clock"],
        "sortie": ["figure.walk", "arrow.up.forward"],
        "soiree": ["moon.stars", "wineglass"],
        "fete": ["party.popper", "balloon.2"],
        "anniversaire": ["birthday.cake", "gift"],
        "vacances": ["beach.umbrella", "suitcase"],
        "concert": ["music.note", "guitars"],
        "expo": ["building.columns", "photo"],
        "biblio": ["books.vertical"],
        "colloc": ["house", "person.2"],

        // MARK: Sports et loisirs
        "tennis": ["figure.tennis", "tennisball"],
        "foot": ["figure.soccer", "soccerball"],
        "basket": ["figure.basketball", "basketball"],
        "danse": ["figure.dance"],
        "yoga": ["figure.yoga"],
        "musculation": ["dumbbell", "figure.strengthtraining.traditional"],
        "escalade": ["figure.climbing"],
        "ski": ["figure.skiing.downhill"],
        "randonnee": ["figure.hiking"],
        "rando": ["figure.hiking"],
        "natation": ["figure.pool.swim"],

        // MARK: Services
        "garage": ["wrench.and.screwdriver", "car"],
        "atelier": ["hammer", "wrench.and.screwdriver"],
        "mairie": ["building.columns"],
        "tribunal": ["building.columns"],
        "police": ["shield", "textformat"],
        "pompier": ["flame"],
        "veterinaire": ["pawprint", "stethoscope"],
        "opticien": ["eyeglasses"],
        "assurance": ["shield"],
        "notaire": ["doc.text"],
        "hosto": ["cross", "stethoscope"],
        "kine": ["figure.walk", "cross.case"],
        "psy": ["brain"],
        "labo": ["cross.vial", "testtube.2"],
        "boulangerie": ["fork.knife", "bag"],
        "epicerie": ["cart", "basket"],
        "laverie": ["washer"],
        "pressing": ["washer"],

        // MARK: English
        "house": ["house"],
        "job": ["briefcase"],
        "class": ["graduationcap"],
        "college": ["graduationcap"],
        "campus": ["graduationcap", "building.columns"],
        "airport": ["airplane"],
        "bike": ["bicycle"],
        "walk": ["figure.walk"],
        "doctor": ["stethoscope"],
        "hospital": ["cross", "stethoscope"],
        "pharmacy": ["cross", "pills"],
        "groceries": ["cart", "basket"],
        "shopping": ["bag", "cart"],
        "friend": ["person.2"],
        "family": ["figure.2.and.child.holdinghands"],
        "mom": ["person"],
        "mum": ["person"],
        "dad": ["person"],
        "grandma": ["person"],
        "grandpa": ["person"],
        "kid": ["figure.child"],
        "daycare": ["figure.child", "stroller"],
        "cabin": ["house.lodge"],
        "holiday": ["beach.umbrella", "suitcase"],
        "vacation": ["beach.umbrella", "suitcase"],
        "party": ["party.popper", "balloon.2"],
        "meeting": ["person.3", "calendar"],
        "appointment": ["calendar", "clock"],
        "movies": ["film"],
        "coffee": ["cup.and.saucer"],
        "pub": ["wineglass"],
        "church": ["building.columns"],
        "library": ["books.vertical"],
        "museum": ["building.columns"],
        "pool": ["figure.pool.swim", "water.waves"],
        "barber": ["scissors"],
        "hairdresser": ["scissors"],
        "vet": ["pawprint", "stethoscope"],
        "dentist": ["mouth"],
        "bank": ["building.columns", "creditcard"],
        "gas": ["fuelpump"],
        "petrol": ["fuelpump"],
        "commute": ["tram", "figure.walk"],
        "trip": ["map", "suitcase"]

    ]
}
